#!/usr/bin/env bash
# install a Nginx web server
sudo apt -y update
sudo apt -y install nginx
sudo sed -i "s/8080(w+/80/g" "/etc/nginx/sites-enabled/default"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx restart
