#!/usr/bin/env bash
# install a Nginx web server
cmmd='location = /redirect_me\n\t{\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\n\t}'
sudo apt -y update
sudo apt -y install nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bukup
sudo sed -i "/server_name _;/a${cmmd}" /etc/nginx/sites-available/default
echo "Hello World!" > "/var/www/html/index.nginx-debian.html"
sudo /etc/init.d/nginx restart