#!/usr/bin/env bash
# install a Nginx web server
redirect_config='location = /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}'
e404='error_page 404 /404.html;\nlocation = /404.html {root /var/www/html/;}'
sudo apt -y update
sudo apt -y install nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
sudo sed -i "/server_name _;/a${redirect_config}" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a${e404}" /etc/nginx/sites-available/default
echo "Hello World!" > "/var/www/html/index.nginx-debian.html"
echo "Ceci n'est pas une page" > "/var/www/html/404.html"
service nginx restart
