#!/usr/bin/env bash
# bash script that change home ip

cp /etc/hosts ~/hosts.new
sed "s/127.0.0.1	localhost/127.0.0.2	localhost/" ~/hosts.new

echo "8.8.8.8	facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
